const data = [
  {
    id: 1,
    category: "UI/UX",
    image: "",
    title: "FortuneTrack - Design",
    desc: "Provident similique accusantium nemo autem. Veritatis obcaecati tenetur iure eius earum ut molestias architecto voluptate aliquam nihil, eveniet aliquid culpa officia aut!",
    demo: "https://www.figma.com/design/HXmTERwjHOYsptklvTHAkW/FortuneTrack-Capstone?node-id=0-1&t=y27DDeTniTrKko4h-1",
    github: null, // No GitHub link for UI/UX projects
  },
  {
    id: 2,
    category: "Front-End",
    image: "",
    title: "WeatherWise ++",
    desc: "Provident similique accusantium nemo autem. Veritatis obcaecati tenetur iure eius earum ut molestias architecto voluptate aliquam nihil, eveniet aliquid culpa officia aut!",
    demo: "https://weather-wise-plus.vercel.app/",
    github: "https://github.com/SimanyeSTS/weather-map-app.git",
  },
  {
    id: 3,
    category: "Back-End",
    image: "https://i.postimg.cc/mrfWVnW9/Screenshot-2025-01-13-162054.png",
    title: "FortuneTrack",
    desc: "Provident similique accusantium nemo autem. Veritatis obcaecati tenetur iure eius earum ut molestias architecto voluptate aliquam nihil, eveniet aliquid culpa officia aut!",
    demo: "https://fortunetrack-91faa.web.app/",
    github: "https://github.com/SimanyeSTS/FortuneTrack.git",
  },
  {
    id: 4,
    category: "UI/UX",
    image: "",
    title: "VueJS Portfolio - Design",
    desc: "Provident similique accusantium nemo autem. Veritatis obcaecati tenetur iure eius earum ut molestias architecto voluptate aliquam nihil, eveniet aliquid culpa officia aut!",
    demo: "https://www.figma.com/design/uRPLAZmDEjBFdNfsV74CbQ/Vue.js-Portfolio?node-id=0-1&t=YEnBk8fTdvgbevzP-1",
    github: null, // No GitHub link for UI/UX projects
  },
  {
    id: 5,
    category: "UI/UX",
    image: "",
    title: "Snack Shack - Design",
    desc: "Provident similique accusantium nemo autem. Veritatis obcaecati tenetur iure eius earum ut molestias architecto voluptate aliquam nihil, eveniet aliquid culpa officia aut! ",
    demo: "https://www.figma.com/design/UwJTS7YCLV0X1r3ncT3s3J/Fast-Food-Snack-Shack?node-id=0-1&t=aRXdCMZERagPlnqa-1",
    github: null, // No GitHub link for UI/UX projects
  },
  {
    id: 6,
    category: "Front-End",
    image: "",
    title: "VueJS Portfolio",
    desc: "Provident similique accusantium nemo autem. Veritatis obcaecati tenetur iure eius earum ut molestias architecto voluptate aliquam nihil, eveniet aliquid culpa officia aut!",
    demo: "https://simanye-somdaka-s-portfolio.web.app/",
    github: "https://github.com/SimanyeSTS/finalPortfolio1.git",
  },
  {
    id: 7,
    category: "Back-End",
    image: "https://i.postimg.cc/SR0JCs2W/Screenshot-2024-09-18-101605.png",
    title: "AuraArtistry",
    desc: "Provident similique accusantium nemo autem. Veritatis obcaecati tenetur iure eius earum ut molestias architecto voluptate aliquam nihil, eveniet aliquid culpa officia aut!",
    demo: "http://egatortutorials.com",
    github: "https://vuejs-frontend-e2fc1.web.app/",
  },
  {
    id: 8,
    category: "Back-End",
    image: "",
    title: "WeatherWise",
    desc: "Provident similique accusantium nemo autem. Veritatis obcaecati tenetur iure eius earum ut molestias architecto voluptate aliquam nihil, eveniet aliquid culpa officia aut!",
    demo: "https://weather-wise-sftw-eng.vercel.app/",
    github: "https://github.com/SimanyeSTS/weather_app.git",
  },
  {
    id: 9,
    category: "Front-End",
    image: "https://i.postimg.cc/ZK0Z4jdy/Screenshot-2024-10-15-152101.png",
    title: "TimeScape",
    desc: "Provident similique accusantium nemo autem. Veritatis obcaecati tenetur iure eius earum ut molestias architecto voluptate aliquam nihil, eveniet aliquid culpa officia aut!",
    demo: "https://clock-work-three.vercel.app/",
    github: "https://github.com/SimanyeSTS/clockWork.git",
  },
];

export default data;